package com.kadir.common.utils.currency;

import com.kadir.common.enums.CurrencyCode;
import com.kadir.modules.currency.model.Currency;

import java.util.HashMap;
import java.util.Map;

public class CurrencyUtils {

    private static final Map<CurrencyCode, String> CURRENCY_NAMES = new HashMap<>();
    private static final Map<CurrencyCode, String> CURRENCY_SYMBOLS = new HashMap<>();
    private static final Map<String, Double> EXCHANGE_RATES = new HashMap<>();

    static {
        CURRENCY_NAMES.put(CurrencyCode.USD, "United States Dollar");
        CURRENCY_NAMES.put(CurrencyCode.AED, "United Arab Emirates Dirham");
        CURRENCY_NAMES.put(CurrencyCode.AFN, "Afghan Afghani");
        CURRENCY_NAMES.put(CurrencyCode.ALL, "Albanian Lek");
        CURRENCY_NAMES.put(CurrencyCode.AMD, "Armenian Dram");
        CURRENCY_NAMES.put(CurrencyCode.ANG, "Netherlands Antillean Guilder");
        CURRENCY_NAMES.put(CurrencyCode.AOA, "Angolan Kwanza");
        CURRENCY_NAMES.put(CurrencyCode.ARS, "Argentine Peso");
        CURRENCY_NAMES.put(CurrencyCode.AUD, "Australian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.AWG, "Aruban Florin");
        CURRENCY_NAMES.put(CurrencyCode.AZN, "Azerbaijani Manat");
        CURRENCY_NAMES.put(CurrencyCode.BAM, "Bosnia-Herzegovina Convertible Mark");
        CURRENCY_NAMES.put(CurrencyCode.BBD, "Barbadian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.BDT, "Bangladeshi Taka");
        CURRENCY_NAMES.put(CurrencyCode.BGN, "Bulgarian Lev");
        CURRENCY_NAMES.put(CurrencyCode.BHD, "Bahraini Dinar");
        CURRENCY_NAMES.put(CurrencyCode.BIF, "Burundian Franc");
        CURRENCY_NAMES.put(CurrencyCode.BMD, "Bermudian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.BND, "Brunei Dollar");
        CURRENCY_NAMES.put(CurrencyCode.BOB, "Bolivian Boliviano");
        CURRENCY_NAMES.put(CurrencyCode.BRL, "Brazilian Real");
        CURRENCY_NAMES.put(CurrencyCode.BSD, "Bahamian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.BTN, "Bhutanese Ngultrum");
        CURRENCY_NAMES.put(CurrencyCode.BWP, "Botswana Pula");
        CURRENCY_NAMES.put(CurrencyCode.BYN, "Belarusian Ruble");
        CURRENCY_NAMES.put(CurrencyCode.BZD, "Belize Dollar");
        CURRENCY_NAMES.put(CurrencyCode.CAD, "Canadian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.CDF, "Congolese Franc");
        CURRENCY_NAMES.put(CurrencyCode.CHF, "Swiss Franc");
        CURRENCY_NAMES.put(CurrencyCode.CLP, "Chilean Peso");
        CURRENCY_NAMES.put(CurrencyCode.CNY, "Chinese Yuan");
        CURRENCY_NAMES.put(CurrencyCode.COP, "Colombian Peso");
        CURRENCY_NAMES.put(CurrencyCode.CRC, "Costa Rican Colón");
        CURRENCY_NAMES.put(CurrencyCode.CUP, "Cuban Peso");
        CURRENCY_NAMES.put(CurrencyCode.CVE, "Cape Verdean Escudo");
        CURRENCY_NAMES.put(CurrencyCode.CZK, "Czech Koruna");
        CURRENCY_NAMES.put(CurrencyCode.DJF, "Djiboutian Franc");
        CURRENCY_NAMES.put(CurrencyCode.DKK, "Danish Krone");
        CURRENCY_NAMES.put(CurrencyCode.DOP, "Dominican Peso");
        CURRENCY_NAMES.put(CurrencyCode.DZD, "Algerian Dinar");
        CURRENCY_NAMES.put(CurrencyCode.EGP, "Egyptian Pound");
        CURRENCY_NAMES.put(CurrencyCode.ERN, "Eritrean Nakfa");
        CURRENCY_NAMES.put(CurrencyCode.ETB, "Ethiopian Birr");
        CURRENCY_NAMES.put(CurrencyCode.EUR, "Euro");
        CURRENCY_NAMES.put(CurrencyCode.FJD, "Fijian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.FKP, "Falkland Islands Pound");
        CURRENCY_NAMES.put(CurrencyCode.FOK, "Faroese Króna");
        CURRENCY_NAMES.put(CurrencyCode.GBP, "British Pound Sterling");
        CURRENCY_NAMES.put(CurrencyCode.GEL, "Georgian Lari");
        CURRENCY_NAMES.put(CurrencyCode.GGP, "Guernsey Pound");
        CURRENCY_NAMES.put(CurrencyCode.GHS, "Ghanaian Cedi");
        CURRENCY_NAMES.put(CurrencyCode.GIP, "Gibraltar Pound");
        CURRENCY_NAMES.put(CurrencyCode.GMD, "Gambian Dalasi");
        CURRENCY_NAMES.put(CurrencyCode.GNF, "Guinean Franc");
        CURRENCY_NAMES.put(CurrencyCode.GTQ, "Guatemalan Quetzal");
        CURRENCY_NAMES.put(CurrencyCode.GYD, "Guyanese Dollar");
        CURRENCY_NAMES.put(CurrencyCode.HKD, "Hong Kong Dollar");
        CURRENCY_NAMES.put(CurrencyCode.HNL, "Honduran Lempira");
        CURRENCY_NAMES.put(CurrencyCode.HRK, "Croatian Kuna");
        CURRENCY_NAMES.put(CurrencyCode.HTG, "Haitian Gourde");
        CURRENCY_NAMES.put(CurrencyCode.HUF, "Hungarian Forint");
        CURRENCY_NAMES.put(CurrencyCode.IDR, "Indonesian Rupiah");
        CURRENCY_NAMES.put(CurrencyCode.ILS, "Israeli New Shekel");
        CURRENCY_NAMES.put(CurrencyCode.IMP, "Isle of Man Pound");
        CURRENCY_NAMES.put(CurrencyCode.INR, "Indian Rupee");
        CURRENCY_NAMES.put(CurrencyCode.IQD, "Iraqi Dinar");
        CURRENCY_NAMES.put(CurrencyCode.IRR, "Iranian Rial");
        CURRENCY_NAMES.put(CurrencyCode.ISK, "Icelandic Króna");
        CURRENCY_NAMES.put(CurrencyCode.JEP, "Jersey Pound");
        CURRENCY_NAMES.put(CurrencyCode.JMD, "Jamaican Dollar");
        CURRENCY_NAMES.put(CurrencyCode.JOD, "Jordanian Dinar");
        CURRENCY_NAMES.put(CurrencyCode.JPY, "Japanese Yen");
        CURRENCY_NAMES.put(CurrencyCode.KES, "Kenyan Shilling");
        CURRENCY_NAMES.put(CurrencyCode.KGS, "Kyrgyzstani Som");
        CURRENCY_NAMES.put(CurrencyCode.KHR, "Cambodian Riel");
        CURRENCY_NAMES.put(CurrencyCode.KID, "Kiribati Dollar");
        CURRENCY_NAMES.put(CurrencyCode.KMF, "Comorian Franc");
        CURRENCY_NAMES.put(CurrencyCode.KRW, "South Korean Won");
        CURRENCY_NAMES.put(CurrencyCode.KWD, "Kuwaiti Dinar");
        CURRENCY_NAMES.put(CurrencyCode.KYD, "Cayman Islands Dollar");
        CURRENCY_NAMES.put(CurrencyCode.KZT, "Kazakhstani Tenge");
        CURRENCY_NAMES.put(CurrencyCode.LAK, "Lao Kip");
        CURRENCY_NAMES.put(CurrencyCode.LBP, "Lebanese Pound");
        CURRENCY_NAMES.put(CurrencyCode.LKR, "Sri Lankan Rupee");
        CURRENCY_NAMES.put(CurrencyCode.LRD, "Liberian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.LSL, "Lesotho Loti");
        CURRENCY_NAMES.put(CurrencyCode.LYD, "Libyan Dinar");
        CURRENCY_NAMES.put(CurrencyCode.MAD, "Moroccan Dirham");
        CURRENCY_NAMES.put(CurrencyCode.MDL, "Moldovan Leu");
        CURRENCY_NAMES.put(CurrencyCode.MGA, "Malagasy Ariary");
        CURRENCY_NAMES.put(CurrencyCode.MKD, "Macedonian Denar");
        CURRENCY_NAMES.put(CurrencyCode.MMK, "Burmese Kyat");
        CURRENCY_NAMES.put(CurrencyCode.MNT, "Mongolian Tögrög");
        CURRENCY_NAMES.put(CurrencyCode.MOP, "Macanese Pataca");
        CURRENCY_NAMES.put(CurrencyCode.MRU, "Mauritanian Ouguiya");
        CURRENCY_NAMES.put(CurrencyCode.MUR, "Mauritian Rupee");
        CURRENCY_NAMES.put(CurrencyCode.MVR, "Maldivian Rufiyaa");
        CURRENCY_NAMES.put(CurrencyCode.MWK, "Malawian Kwacha");
        CURRENCY_NAMES.put(CurrencyCode.MXN, "Mexican Peso");
        CURRENCY_NAMES.put(CurrencyCode.MYR, "Malaysian Ringgit");
        CURRENCY_NAMES.put(CurrencyCode.MZN, "Mozambican Metical");
        CURRENCY_NAMES.put(CurrencyCode.NAD, "Namibian Dollar");
        CURRENCY_NAMES.put(CurrencyCode.NGN, "Nigerian Naira");
        CURRENCY_NAMES.put(CurrencyCode.NIO, "Nicaraguan Córdoba");
        CURRENCY_NAMES.put(CurrencyCode.NOK, "Norwegian Krone");
        CURRENCY_NAMES.put(CurrencyCode.NPR, "Nepalese Rupee");
        CURRENCY_NAMES.put(CurrencyCode.NZD, "New Zealand Dollar");
        CURRENCY_NAMES.put(CurrencyCode.OMR, "Omani Rial");
        CURRENCY_NAMES.put(CurrencyCode.PAB, "Panamanian Balboa");
        CURRENCY_NAMES.put(CurrencyCode.PEN, "Peruvian Sol");
        CURRENCY_NAMES.put(CurrencyCode.PGK, "Papua New Guinean Kina");
        CURRENCY_NAMES.put(CurrencyCode.PHP, "Philippine Peso");
        CURRENCY_NAMES.put(CurrencyCode.PKR, "Pakistani Rupee");
        CURRENCY_NAMES.put(CurrencyCode.PLN, "Polish Złoty");
        CURRENCY_NAMES.put(CurrencyCode.PYG, "Paraguayan Guarani");
        CURRENCY_NAMES.put(CurrencyCode.QAR, "Qatari Riyal");
        CURRENCY_NAMES.put(CurrencyCode.RON, "Romanian Leu");
        CURRENCY_NAMES.put(CurrencyCode.RSD, "Serbian Dinar");
        CURRENCY_NAMES.put(CurrencyCode.RUB, "Russian Ruble");
        CURRENCY_NAMES.put(CurrencyCode.RWF, "Rwandan Franc");
        CURRENCY_NAMES.put(CurrencyCode.SAR, "Saudi Riyal");
        CURRENCY_NAMES.put(CurrencyCode.SBD, "Solomon Islands Dollar");
        CURRENCY_NAMES.put(CurrencyCode.SCR, "Seychellois Rupee");
        CURRENCY_NAMES.put(CurrencyCode.SDG, "Sudanese Pound");
        CURRENCY_NAMES.put(CurrencyCode.SEK, "Swedish Krona");
        CURRENCY_NAMES.put(CurrencyCode.SGD, "Singapore Dollar");
        CURRENCY_NAMES.put(CurrencyCode.SHP, "Saint Helena Pound");
        CURRENCY_NAMES.put(CurrencyCode.SLE, "Sierra Leonean Leone");
        CURRENCY_NAMES.put(CurrencyCode.SLL, "Sierra Leonean Leone");
        CURRENCY_NAMES.put(CurrencyCode.SOS, "Somali Shilling");
        CURRENCY_NAMES.put(CurrencyCode.SRD, "Surinamese Dollar");
        CURRENCY_NAMES.put(CurrencyCode.SSP, "South Sudanese Pound");
        CURRENCY_NAMES.put(CurrencyCode.STN, "São Tomé and Príncipe Dobra");
        CURRENCY_NAMES.put(CurrencyCode.SYP, "Syrian Pound");
        CURRENCY_NAMES.put(CurrencyCode.SZL, "Swazi Lilangeni");
        CURRENCY_NAMES.put(CurrencyCode.THB, "Thai Baht");
        CURRENCY_NAMES.put(CurrencyCode.TJS, "Tajikistani Somoni");
        CURRENCY_NAMES.put(CurrencyCode.TMT, "Turkmenistani Manat");
        CURRENCY_NAMES.put(CurrencyCode.TND, "Tunisian Dinar");
        CURRENCY_NAMES.put(CurrencyCode.TOP, "Tongan Paʻanga");
        CURRENCY_NAMES.put(CurrencyCode.TRY, "Turkish Lira");
        CURRENCY_NAMES.put(CurrencyCode.TTD, "Trinidad and Tobago Dollar");
        CURRENCY_NAMES.put(CurrencyCode.TVD, "Tuvaluan Dollar");
        CURRENCY_NAMES.put(CurrencyCode.TWD, "New Taiwan Dollar");
        CURRENCY_NAMES.put(CurrencyCode.TZS, "Tanzanian Shilling");
        CURRENCY_NAMES.put(CurrencyCode.UAH, "Ukrainian Hryvnia");
        CURRENCY_NAMES.put(CurrencyCode.UGX, "Ugandan Shilling");
        CURRENCY_NAMES.put(CurrencyCode.UYU, "Uruguayan Peso");
        CURRENCY_NAMES.put(CurrencyCode.UZS, "Uzbekistani Som");
        CURRENCY_NAMES.put(CurrencyCode.VES, "Venezuelan Bolívar");
        CURRENCY_NAMES.put(CurrencyCode.VND, "Vietnamese Đồng");
        CURRENCY_NAMES.put(CurrencyCode.VUV, "Vanuatu Vatu");
        CURRENCY_NAMES.put(CurrencyCode.WST, "Samoan Tālā");
        CURRENCY_NAMES.put(CurrencyCode.XAF, "Central African CFA Franc");
        CURRENCY_NAMES.put(CurrencyCode.XCD, "East Caribbean Dollar");
        CURRENCY_NAMES.put(CurrencyCode.XDR, "Special Drawing Rights");
        CURRENCY_NAMES.put(CurrencyCode.XOF, "West African CFA Franc");
        CURRENCY_NAMES.put(CurrencyCode.XPF, "CFP Franc");
        CURRENCY_NAMES.put(CurrencyCode.YER, "Yemeni Rial");
        CURRENCY_NAMES.put(CurrencyCode.ZAR, "South African Rand");
        CURRENCY_NAMES.put(CurrencyCode.ZMW, "Zambian Kwacha");
        CURRENCY_NAMES.put(CurrencyCode.ZWL, "Zimbabwean Dollar");

        CURRENCY_SYMBOLS.put(CurrencyCode.USD, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.AED, "د.إ");
        CURRENCY_SYMBOLS.put(CurrencyCode.AFN, "؋");
        CURRENCY_SYMBOLS.put(CurrencyCode.ALL, "L");
        CURRENCY_SYMBOLS.put(CurrencyCode.AMD, "֏");
        CURRENCY_SYMBOLS.put(CurrencyCode.ANG, "ƒ");
        CURRENCY_SYMBOLS.put(CurrencyCode.AOA, "Kz");
        CURRENCY_SYMBOLS.put(CurrencyCode.ARS, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.AUD, "A$");
        CURRENCY_SYMBOLS.put(CurrencyCode.AWG, "ƒ");
        CURRENCY_SYMBOLS.put(CurrencyCode.AZN, "₼");
        CURRENCY_SYMBOLS.put(CurrencyCode.BAM, "KM");
        CURRENCY_SYMBOLS.put(CurrencyCode.BBD, "Bds$");
        CURRENCY_SYMBOLS.put(CurrencyCode.BDT, "৳");
        CURRENCY_SYMBOLS.put(CurrencyCode.BGN, "лв");
        CURRENCY_SYMBOLS.put(CurrencyCode.BHD, ".د.ب");
        CURRENCY_SYMBOLS.put(CurrencyCode.BIF, "FBu");
        CURRENCY_SYMBOLS.put(CurrencyCode.BMD, "BD$");
        CURRENCY_SYMBOLS.put(CurrencyCode.BND, "B$");
        CURRENCY_SYMBOLS.put(CurrencyCode.BOB, "Bs.");
        CURRENCY_SYMBOLS.put(CurrencyCode.BRL, "R$");
        CURRENCY_SYMBOLS.put(CurrencyCode.BSD, "B$");
        CURRENCY_SYMBOLS.put(CurrencyCode.BTN, "Nu.");
        CURRENCY_SYMBOLS.put(CurrencyCode.BWP, "P");
        CURRENCY_SYMBOLS.put(CurrencyCode.BYN, "Br");
        CURRENCY_SYMBOLS.put(CurrencyCode.BZD, "BZ$");
        CURRENCY_SYMBOLS.put(CurrencyCode.CAD, "C$");
        CURRENCY_SYMBOLS.put(CurrencyCode.CDF, "FC");
        CURRENCY_SYMBOLS.put(CurrencyCode.CHF, "CHF");
        CURRENCY_SYMBOLS.put(CurrencyCode.CLP, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.CNY, "¥");
        CURRENCY_SYMBOLS.put(CurrencyCode.COP, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.CRC, "₡");
        CURRENCY_SYMBOLS.put(CurrencyCode.CUP, "₱");
        CURRENCY_SYMBOLS.put(CurrencyCode.CVE, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.CZK, "Kč");
        CURRENCY_SYMBOLS.put(CurrencyCode.DJF, "Fdj");
        CURRENCY_SYMBOLS.put(CurrencyCode.DKK, "kr");
        CURRENCY_SYMBOLS.put(CurrencyCode.DOP, "RD$");
        CURRENCY_SYMBOLS.put(CurrencyCode.DZD, "دج");
        CURRENCY_SYMBOLS.put(CurrencyCode.EGP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.ERN, "Nkf");
        CURRENCY_SYMBOLS.put(CurrencyCode.ETB, "Br");
        CURRENCY_SYMBOLS.put(CurrencyCode.EUR, "€");
        CURRENCY_SYMBOLS.put(CurrencyCode.FJD, "FJ$");
        CURRENCY_SYMBOLS.put(CurrencyCode.FKP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.FOK, "kr");
        CURRENCY_SYMBOLS.put(CurrencyCode.GBP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.GEL, "₾");
        CURRENCY_SYMBOLS.put(CurrencyCode.GGP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.GHS, "₵");
        CURRENCY_SYMBOLS.put(CurrencyCode.GIP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.GMD, "D");
        CURRENCY_SYMBOLS.put(CurrencyCode.GNF, "FG");
        CURRENCY_SYMBOLS.put(CurrencyCode.GTQ, "Q");
        CURRENCY_SYMBOLS.put(CurrencyCode.GYD, "GY$");
        CURRENCY_SYMBOLS.put(CurrencyCode.HKD, "HK$");
        CURRENCY_SYMBOLS.put(CurrencyCode.HNL, "L");
        CURRENCY_SYMBOLS.put(CurrencyCode.HRK, "kn");
        CURRENCY_SYMBOLS.put(CurrencyCode.HTG, "G");
        CURRENCY_SYMBOLS.put(CurrencyCode.HUF, "Ft");
        CURRENCY_SYMBOLS.put(CurrencyCode.IDR, "Rp");
        CURRENCY_SYMBOLS.put(CurrencyCode.ILS, "₪");
        CURRENCY_SYMBOLS.put(CurrencyCode.IMP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.INR, "₹");
        CURRENCY_SYMBOLS.put(CurrencyCode.IQD, "ع.د");
        CURRENCY_SYMBOLS.put(CurrencyCode.IRR, "﷼");
        CURRENCY_SYMBOLS.put(CurrencyCode.ISK, "kr");
        CURRENCY_SYMBOLS.put(CurrencyCode.JEP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.JMD, "J$");
        CURRENCY_SYMBOLS.put(CurrencyCode.JOD, "د.ا");
        CURRENCY_SYMBOLS.put(CurrencyCode.JPY, "¥");
        CURRENCY_SYMBOLS.put(CurrencyCode.KES, "KSh");
        CURRENCY_SYMBOLS.put(CurrencyCode.KGS, "с");
        CURRENCY_SYMBOLS.put(CurrencyCode.KHR, "៛");
        CURRENCY_SYMBOLS.put(CurrencyCode.KID, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.KMF, "CF");
        CURRENCY_SYMBOLS.put(CurrencyCode.KRW, "₩");
        CURRENCY_SYMBOLS.put(CurrencyCode.KWD, "د.ك");
        CURRENCY_SYMBOLS.put(CurrencyCode.KYD, "CI$");
        CURRENCY_SYMBOLS.put(CurrencyCode.KZT, "₸");
        CURRENCY_SYMBOLS.put(CurrencyCode.LAK, "₭");
        CURRENCY_SYMBOLS.put(CurrencyCode.LBP, "ل.ل");
        CURRENCY_SYMBOLS.put(CurrencyCode.LKR, "Rs");
        CURRENCY_SYMBOLS.put(CurrencyCode.LRD, "L$");
        CURRENCY_SYMBOLS.put(CurrencyCode.LSL, "L");
        CURRENCY_SYMBOLS.put(CurrencyCode.LYD, "ل.د");
        CURRENCY_SYMBOLS.put(CurrencyCode.MAD, "د.م.");
        CURRENCY_SYMBOLS.put(CurrencyCode.MDL, "L");
        CURRENCY_SYMBOLS.put(CurrencyCode.MGA, "Ar");
        CURRENCY_SYMBOLS.put(CurrencyCode.MKD, "ден");
        CURRENCY_SYMBOLS.put(CurrencyCode.MMK, "K");
        CURRENCY_SYMBOLS.put(CurrencyCode.MNT, "₮");
        CURRENCY_SYMBOLS.put(CurrencyCode.MOP, "MOP$");
        CURRENCY_SYMBOLS.put(CurrencyCode.MRU, "UM");
        CURRENCY_SYMBOLS.put(CurrencyCode.MUR, "₨");
        CURRENCY_SYMBOLS.put(CurrencyCode.MVR, "ރ.");
        CURRENCY_SYMBOLS.put(CurrencyCode.MWK, "MK");
        CURRENCY_SYMBOLS.put(CurrencyCode.MXN, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.MYR, "RM");
        CURRENCY_SYMBOLS.put(CurrencyCode.MZN, "MT");
        CURRENCY_SYMBOLS.put(CurrencyCode.NAD, "N$");
        CURRENCY_SYMBOLS.put(CurrencyCode.NGN, "₦");
        CURRENCY_SYMBOLS.put(CurrencyCode.NIO, "C$");
        CURRENCY_SYMBOLS.put(CurrencyCode.NOK, "kr");
        CURRENCY_SYMBOLS.put(CurrencyCode.NPR, "₨");
        CURRENCY_SYMBOLS.put(CurrencyCode.NZD, "NZ$");
        CURRENCY_SYMBOLS.put(CurrencyCode.OMR, "ر.ع.");
        CURRENCY_SYMBOLS.put(CurrencyCode.PAB, "B/.");
        CURRENCY_SYMBOLS.put(CurrencyCode.PEN, "S/.");
        CURRENCY_SYMBOLS.put(CurrencyCode.PGK, "K");
        CURRENCY_SYMBOLS.put(CurrencyCode.PHP, "₱");
        CURRENCY_SYMBOLS.put(CurrencyCode.PKR, "₨");
        CURRENCY_SYMBOLS.put(CurrencyCode.PLN, "zł");
        CURRENCY_SYMBOLS.put(CurrencyCode.PYG, "₲");
        CURRENCY_SYMBOLS.put(CurrencyCode.QAR, "ر.ق");
        CURRENCY_SYMBOLS.put(CurrencyCode.RON, "lei");
        CURRENCY_SYMBOLS.put(CurrencyCode.RSD, "дин.");
        CURRENCY_SYMBOLS.put(CurrencyCode.RUB, "₽");
        CURRENCY_SYMBOLS.put(CurrencyCode.RWF, "FRw");
        CURRENCY_SYMBOLS.put(CurrencyCode.SAR, "ر.س");
        CURRENCY_SYMBOLS.put(CurrencyCode.SBD, "SI$");
        CURRENCY_SYMBOLS.put(CurrencyCode.SCR, "₨");
        CURRENCY_SYMBOLS.put(CurrencyCode.SDG, "ج.س.");
        CURRENCY_SYMBOLS.put(CurrencyCode.SEK, "kr");
        CURRENCY_SYMBOLS.put(CurrencyCode.SGD, "S$");
        CURRENCY_SYMBOLS.put(CurrencyCode.SHP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.SLE, "Le");
        CURRENCY_SYMBOLS.put(CurrencyCode.SLL, "Le");
        CURRENCY_SYMBOLS.put(CurrencyCode.SOS, "Sh");
        CURRENCY_SYMBOLS.put(CurrencyCode.SRD, "SR$");
        CURRENCY_SYMBOLS.put(CurrencyCode.SSP, "£");
        CURRENCY_SYMBOLS.put(CurrencyCode.STN, "Db");
        CURRENCY_SYMBOLS.put(CurrencyCode.SYP, "ل.س");
        CURRENCY_SYMBOLS.put(CurrencyCode.SZL, "L");
        CURRENCY_SYMBOLS.put(CurrencyCode.THB, "฿");
        CURRENCY_SYMBOLS.put(CurrencyCode.TJS, "ЅМ");
        CURRENCY_SYMBOLS.put(CurrencyCode.TMT, "m");
        CURRENCY_SYMBOLS.put(CurrencyCode.TND, "د.ت");
        CURRENCY_SYMBOLS.put(CurrencyCode.TOP, "T$");
        CURRENCY_SYMBOLS.put(CurrencyCode.TRY, "₺");
        CURRENCY_SYMBOLS.put(CurrencyCode.TTD, "TT$");
        CURRENCY_SYMBOLS.put(CurrencyCode.TVD, "$");
        CURRENCY_SYMBOLS.put(CurrencyCode.TWD, "NT$");
        CURRENCY_SYMBOLS.put(CurrencyCode.TZS, "TSh");
        CURRENCY_SYMBOLS.put(CurrencyCode.UAH, "₴");
        CURRENCY_SYMBOLS.put(CurrencyCode.UGX, "USh");
        CURRENCY_SYMBOLS.put(CurrencyCode.UYU, "$U");
        CURRENCY_SYMBOLS.put(CurrencyCode.UZS, "so'm");
        CURRENCY_SYMBOLS.put(CurrencyCode.VES, "Bs.");
        CURRENCY_SYMBOLS.put(CurrencyCode.VND, "₫");
        CURRENCY_SYMBOLS.put(CurrencyCode.VUV, "VT");
        CURRENCY_SYMBOLS.put(CurrencyCode.WST, "WS$");
        CURRENCY_SYMBOLS.put(CurrencyCode.XAF, "FCFA");
        CURRENCY_SYMBOLS.put(CurrencyCode.XCD, "EC$");
        CURRENCY_SYMBOLS.put(CurrencyCode.XDR, "SDR");
        CURRENCY_SYMBOLS.put(CurrencyCode.XOF, "CFA");
        CURRENCY_SYMBOLS.put(CurrencyCode.XPF, "₣");
        CURRENCY_SYMBOLS.put(CurrencyCode.YER, "﷼");
        CURRENCY_SYMBOLS.put(CurrencyCode.ZAR, "R");
        CURRENCY_SYMBOLS.put(CurrencyCode.ZMW, "ZK");
        CURRENCY_SYMBOLS.put(CurrencyCode.ZWL, "Z$");
    }

    public static Currency getCurrency(CurrencyCode currencyCode) {
        Currency currency = new Currency();

        currency.setCurrencyCode(currencyCode);
        currency.setCurrencyName(CURRENCY_NAMES.getOrDefault(currencyCode, "Unknown CurrencyCode"));
        currency.setSymbol(CURRENCY_SYMBOLS.getOrDefault(currencyCode, ""));
        currency.setExchangeRate(EXCHANGE_RATES.getOrDefault(currencyCode, 0.0));

        return currency;
    }
}
