package com.kadir.common.utils.currency;

import com.kadir.modules.currency.model.Currency;

import java.util.HashMap;
import java.util.Map;

public class CurrencyUtils {

    private static final Map<String, String> CURRENCY_NAMES = new HashMap<>();
    private static final Map<String, String> CURRENCY_SYMBOLS = new HashMap<>();
    private static final Map<String, Double> EXCHANGE_RATES = new HashMap<>();

    static {
        CURRENCY_NAMES.put("USD", "United States Dollar");
        CURRENCY_NAMES.put("AED", "United Arab Emirates Dirham");
        CURRENCY_NAMES.put("AFN", "Afghan Afghani");
        CURRENCY_NAMES.put("ALL", "Albanian Lek");
        CURRENCY_NAMES.put("AMD", "Armenian Dram");
        CURRENCY_NAMES.put("ANG", "Netherlands Antillean Guilder");
        CURRENCY_NAMES.put("AOA", "Angolan Kwanza");
        CURRENCY_NAMES.put("ARS", "Argentine Peso");
        CURRENCY_NAMES.put("AUD", "Australian Dollar");
        CURRENCY_NAMES.put("AWG", "Aruban Florin");
        CURRENCY_NAMES.put("AZN", "Azerbaijani Manat");
        CURRENCY_NAMES.put("BAM", "Bosnia-Herzegovina Convertible Mark");
        CURRENCY_NAMES.put("BBD", "Barbadian Dollar");
        CURRENCY_NAMES.put("BDT", "Bangladeshi Taka");
        CURRENCY_NAMES.put("BGN", "Bulgarian Lev");
        CURRENCY_NAMES.put("BHD", "Bahraini Dinar");
        CURRENCY_NAMES.put("BIF", "Burundian Franc");
        CURRENCY_NAMES.put("BMD", "Bermudian Dollar");
        CURRENCY_NAMES.put("BND", "Brunei Dollar");
        CURRENCY_NAMES.put("BOB", "Bolivian Boliviano");
        CURRENCY_NAMES.put("BRL", "Brazilian Real");
        CURRENCY_NAMES.put("BSD", "Bahamian Dollar");
        CURRENCY_NAMES.put("BTN", "Bhutanese Ngultrum");
        CURRENCY_NAMES.put("BWP", "Botswana Pula");
        CURRENCY_NAMES.put("BYN", "Belarusian Ruble");
        CURRENCY_NAMES.put("BZD", "Belize Dollar");
        CURRENCY_NAMES.put("CAD", "Canadian Dollar");
        CURRENCY_NAMES.put("CDF", "Congolese Franc");
        CURRENCY_NAMES.put("CHF", "Swiss Franc");
        CURRENCY_NAMES.put("CLP", "Chilean Peso");
        CURRENCY_NAMES.put("CNY", "Chinese Yuan");
        CURRENCY_NAMES.put("COP", "Colombian Peso");
        CURRENCY_NAMES.put("CRC", "Costa Rican Colón");
        CURRENCY_NAMES.put("CUP", "Cuban Peso");
        CURRENCY_NAMES.put("CVE", "Cape Verdean Escudo");
        CURRENCY_NAMES.put("CZK", "Czech Koruna");
        CURRENCY_NAMES.put("DJF", "Djiboutian Franc");
        CURRENCY_NAMES.put("DKK", "Danish Krone");
        CURRENCY_NAMES.put("DOP", "Dominican Peso");
        CURRENCY_NAMES.put("DZD", "Algerian Dinar");
        CURRENCY_NAMES.put("EGP", "Egyptian Pound");
        CURRENCY_NAMES.put("ERN", "Eritrean Nakfa");
        CURRENCY_NAMES.put("ETB", "Ethiopian Birr");
        CURRENCY_NAMES.put("EUR", "Euro");
        CURRENCY_NAMES.put("FJD", "Fijian Dollar");
        CURRENCY_NAMES.put("FKP", "Falkland Islands Pound");
        CURRENCY_NAMES.put("FOK", "Faroese Króna");
        CURRENCY_NAMES.put("GBP", "British Pound Sterling");
        CURRENCY_NAMES.put("GEL", "Georgian Lari");
        CURRENCY_NAMES.put("GGP", "Guernsey Pound");
        CURRENCY_NAMES.put("GHS", "Ghanaian Cedi");
        CURRENCY_NAMES.put("GIP", "Gibraltar Pound");
        CURRENCY_NAMES.put("GMD", "Gambian Dalasi");
        CURRENCY_NAMES.put("GNF", "Guinean Franc");
        CURRENCY_NAMES.put("GTQ", "Guatemalan Quetzal");
        CURRENCY_NAMES.put("GYD", "Guyanese Dollar");
        CURRENCY_NAMES.put("HKD", "Hong Kong Dollar");
        CURRENCY_NAMES.put("HNL", "Honduran Lempira");
        CURRENCY_NAMES.put("HRK", "Croatian Kuna");
        CURRENCY_NAMES.put("HTG", "Haitian Gourde");
        CURRENCY_NAMES.put("HUF", "Hungarian Forint");
        CURRENCY_NAMES.put("IDR", "Indonesian Rupiah");
        CURRENCY_NAMES.put("ILS", "Israeli New Shekel");
        CURRENCY_NAMES.put("IMP", "Isle of Man Pound");
        CURRENCY_NAMES.put("INR", "Indian Rupee");
        CURRENCY_NAMES.put("IQD", "Iraqi Dinar");
        CURRENCY_NAMES.put("IRR", "Iranian Rial");
        CURRENCY_NAMES.put("ISK", "Icelandic Króna");
        CURRENCY_NAMES.put("JEP", "Jersey Pound");
        CURRENCY_NAMES.put("JMD", "Jamaican Dollar");
        CURRENCY_NAMES.put("JOD", "Jordanian Dinar");
        CURRENCY_NAMES.put("JPY", "Japanese Yen");
        CURRENCY_NAMES.put("KES", "Kenyan Shilling");
        CURRENCY_NAMES.put("KGS", "Kyrgyzstani Som");
        CURRENCY_NAMES.put("KHR", "Cambodian Riel");
        CURRENCY_NAMES.put("KID", "Kiribati Dollar");
        CURRENCY_NAMES.put("KMF", "Comorian Franc");
        CURRENCY_NAMES.put("KRW", "South Korean Won");
        CURRENCY_NAMES.put("KWD", "Kuwaiti Dinar");
        CURRENCY_NAMES.put("KYD", "Cayman Islands Dollar");
        CURRENCY_NAMES.put("KZT", "Kazakhstani Tenge");
        CURRENCY_NAMES.put("LAK", "Lao Kip");
        CURRENCY_NAMES.put("LBP", "Lebanese Pound");
        CURRENCY_NAMES.put("LKR", "Sri Lankan Rupee");
        CURRENCY_NAMES.put("LRD", "Liberian Dollar");
        CURRENCY_NAMES.put("LSL", "Lesotho Loti");
        CURRENCY_NAMES.put("LYD", "Libyan Dinar");
        CURRENCY_NAMES.put("MAD", "Moroccan Dirham");
        CURRENCY_NAMES.put("MDL", "Moldovan Leu");
        CURRENCY_NAMES.put("MGA", "Malagasy Ariary");
        CURRENCY_NAMES.put("MKD", "Macedonian Denar");
        CURRENCY_NAMES.put("MMK", "Burmese Kyat");
        CURRENCY_NAMES.put("MNT", "Mongolian Tögrög");
        CURRENCY_NAMES.put("MOP", "Macanese Pataca");
        CURRENCY_NAMES.put("MRU", "Mauritanian Ouguiya");
        CURRENCY_NAMES.put("MUR", "Mauritian Rupee");
        CURRENCY_NAMES.put("MVR", "Maldivian Rufiyaa");
        CURRENCY_NAMES.put("MWK", "Malawian Kwacha");
        CURRENCY_NAMES.put("MXN", "Mexican Peso");
        CURRENCY_NAMES.put("MYR", "Malaysian Ringgit");
        CURRENCY_NAMES.put("MZN", "Mozambican Metical");
        CURRENCY_NAMES.put("NAD", "Namibian Dollar");
        CURRENCY_NAMES.put("NGN", "Nigerian Naira");
        CURRENCY_NAMES.put("NIO", "Nicaraguan Córdoba");
        CURRENCY_NAMES.put("NOK", "Norwegian Krone");
        CURRENCY_NAMES.put("NPR", "Nepalese Rupee");
        CURRENCY_NAMES.put("NZD", "New Zealand Dollar");
        CURRENCY_NAMES.put("OMR", "Omani Rial");
        CURRENCY_NAMES.put("PAB", "Panamanian Balboa");
        CURRENCY_NAMES.put("PEN", "Peruvian Sol");
        CURRENCY_NAMES.put("PGK", "Papua New Guinean Kina");
        CURRENCY_NAMES.put("PHP", "Philippine Peso");
        CURRENCY_NAMES.put("PKR", "Pakistani Rupee");
        CURRENCY_NAMES.put("PLN", "Polish Złoty");
        CURRENCY_NAMES.put("PYG", "Paraguayan Guarani");
        CURRENCY_NAMES.put("QAR", "Qatari Riyal");
        CURRENCY_NAMES.put("RON", "Romanian Leu");
        CURRENCY_NAMES.put("RSD", "Serbian Dinar");
        CURRENCY_NAMES.put("RUB", "Russian Ruble");
        CURRENCY_NAMES.put("RWF", "Rwandan Franc");
        CURRENCY_NAMES.put("SAR", "Saudi Riyal");
        CURRENCY_NAMES.put("SBD", "Solomon Islands Dollar");
        CURRENCY_NAMES.put("SCR", "Seychellois Rupee");
        CURRENCY_NAMES.put("SDG", "Sudanese Pound");
        CURRENCY_NAMES.put("SEK", "Swedish Krona");
        CURRENCY_NAMES.put("SGD", "Singapore Dollar");
        CURRENCY_NAMES.put("SHP", "Saint Helena Pound");
        CURRENCY_NAMES.put("SLE", "Sierra Leonean Leone");
        CURRENCY_NAMES.put("SLL", "Sierra Leonean Leone");
        CURRENCY_NAMES.put("SOS", "Somali Shilling");
        CURRENCY_NAMES.put("SRD", "Surinamese Dollar");
        CURRENCY_NAMES.put("SSP", "South Sudanese Pound");
        CURRENCY_NAMES.put("STN", "São Tomé and Príncipe Dobra");
        CURRENCY_NAMES.put("SYP", "Syrian Pound");
        CURRENCY_NAMES.put("SZL", "Swazi Lilangeni");
        CURRENCY_NAMES.put("THB", "Thai Baht");
        CURRENCY_NAMES.put("TJS", "Tajikistani Somoni");
        CURRENCY_NAMES.put("TMT", "Turkmenistani Manat");
        CURRENCY_NAMES.put("TND", "Tunisian Dinar");
        CURRENCY_NAMES.put("TOP", "Tongan Paʻanga");
        CURRENCY_NAMES.put("TRY", "Turkish Lira");
        CURRENCY_NAMES.put("TTD", "Trinidad and Tobago Dollar");
        CURRENCY_NAMES.put("TVD", "Tuvaluan Dollar");
        CURRENCY_NAMES.put("TWD", "New Taiwan Dollar");
        CURRENCY_NAMES.put("TZS", "Tanzanian Shilling");
        CURRENCY_NAMES.put("UAH", "Ukrainian Hryvnia");
        CURRENCY_NAMES.put("UGX", "Ugandan Shilling");
        CURRENCY_NAMES.put("UYU", "Uruguayan Peso");
        CURRENCY_NAMES.put("UZS", "Uzbekistani Som");
        CURRENCY_NAMES.put("VES", "Venezuelan Bolívar");
        CURRENCY_NAMES.put("VND", "Vietnamese Đồng");
        CURRENCY_NAMES.put("VUV", "Vanuatu Vatu");
        CURRENCY_NAMES.put("WST", "Samoan Tālā");
        CURRENCY_NAMES.put("XAF", "Central African CFA Franc");
        CURRENCY_NAMES.put("XCD", "East Caribbean Dollar");
        CURRENCY_NAMES.put("XDR", "Special Drawing Rights");
        CURRENCY_NAMES.put("XOF", "West African CFA Franc");
        CURRENCY_NAMES.put("XPF", "CFP Franc");
        CURRENCY_NAMES.put("YER", "Yemeni Rial");
        CURRENCY_NAMES.put("ZAR", "South African Rand");
        CURRENCY_NAMES.put("ZMW", "Zambian Kwacha");
        CURRENCY_NAMES.put("ZWL", "Zimbabwean Dollar");

        CURRENCY_SYMBOLS.put("USD", "$");
        CURRENCY_SYMBOLS.put("AED", "د.إ");
        CURRENCY_SYMBOLS.put("AFN", "؋");
        CURRENCY_SYMBOLS.put("ALL", "L");
        CURRENCY_SYMBOLS.put("AMD", "֏");
        CURRENCY_SYMBOLS.put("ANG", "ƒ");
        CURRENCY_SYMBOLS.put("AOA", "Kz");
        CURRENCY_SYMBOLS.put("ARS", "$");
        CURRENCY_SYMBOLS.put("AUD", "A$");
        CURRENCY_SYMBOLS.put("AWG", "ƒ");
        CURRENCY_SYMBOLS.put("AZN", "₼");
        CURRENCY_SYMBOLS.put("BAM", "KM");
        CURRENCY_SYMBOLS.put("BBD", "Bds$");
        CURRENCY_SYMBOLS.put("BDT", "৳");
        CURRENCY_SYMBOLS.put("BGN", "лв");
        CURRENCY_SYMBOLS.put("BHD", ".د.ب");
        CURRENCY_SYMBOLS.put("BIF", "FBu");
        CURRENCY_SYMBOLS.put("BMD", "BD$");
        CURRENCY_SYMBOLS.put("BND", "B$");
        CURRENCY_SYMBOLS.put("BOB", "Bs.");
        CURRENCY_SYMBOLS.put("BRL", "R$");
        CURRENCY_SYMBOLS.put("BSD", "B$");
        CURRENCY_SYMBOLS.put("BTN", "Nu.");
        CURRENCY_SYMBOLS.put("BWP", "P");
        CURRENCY_SYMBOLS.put("BYN", "Br");
        CURRENCY_SYMBOLS.put("BZD", "BZ$");
        CURRENCY_SYMBOLS.put("CAD", "C$");
        CURRENCY_SYMBOLS.put("CDF", "FC");
        CURRENCY_SYMBOLS.put("CHF", "CHF");
        CURRENCY_SYMBOLS.put("CLP", "$");
        CURRENCY_SYMBOLS.put("CNY", "¥");
        CURRENCY_SYMBOLS.put("COP", "$");
        CURRENCY_SYMBOLS.put("CRC", "₡");
        CURRENCY_SYMBOLS.put("CUP", "₱");
        CURRENCY_SYMBOLS.put("CVE", "$");
        CURRENCY_SYMBOLS.put("CZK", "Kč");
        CURRENCY_SYMBOLS.put("DJF", "Fdj");
        CURRENCY_SYMBOLS.put("DKK", "kr");
        CURRENCY_SYMBOLS.put("DOP", "RD$");
        CURRENCY_SYMBOLS.put("DZD", "دج");
        CURRENCY_SYMBOLS.put("EGP", "£");
        CURRENCY_SYMBOLS.put("ERN", "Nkf");
        CURRENCY_SYMBOLS.put("ETB", "Br");
        CURRENCY_SYMBOLS.put("EUR", "€");
        CURRENCY_SYMBOLS.put("FJD", "FJ$");
        CURRENCY_SYMBOLS.put("FKP", "£");
        CURRENCY_SYMBOLS.put("FOK", "kr");
        CURRENCY_SYMBOLS.put("GBP", "£");
        CURRENCY_SYMBOLS.put("GEL", "₾");
        CURRENCY_SYMBOLS.put("GGP", "£");
        CURRENCY_SYMBOLS.put("GHS", "₵");
        CURRENCY_SYMBOLS.put("GIP", "£");
        CURRENCY_SYMBOLS.put("GMD", "D");
        CURRENCY_SYMBOLS.put("GNF", "FG");
        CURRENCY_SYMBOLS.put("GTQ", "Q");
        CURRENCY_SYMBOLS.put("GYD", "GY$");
        CURRENCY_SYMBOLS.put("HKD", "HK$");
        CURRENCY_SYMBOLS.put("HNL", "L");
        CURRENCY_SYMBOLS.put("HRK", "kn");
        CURRENCY_SYMBOLS.put("HTG", "G");
        CURRENCY_SYMBOLS.put("HUF", "Ft");
        CURRENCY_SYMBOLS.put("IDR", "Rp");
        CURRENCY_SYMBOLS.put("ILS", "₪");
        CURRENCY_SYMBOLS.put("IMP", "£");
        CURRENCY_SYMBOLS.put("INR", "₹");
        CURRENCY_SYMBOLS.put("IQD", "ع.د");
        CURRENCY_SYMBOLS.put("IRR", "﷼");
        CURRENCY_SYMBOLS.put("ISK", "kr");
        CURRENCY_SYMBOLS.put("JEP", "£");
        CURRENCY_SYMBOLS.put("JMD", "J$");
        CURRENCY_SYMBOLS.put("JOD", "د.ا");
        CURRENCY_SYMBOLS.put("JPY", "¥");
        CURRENCY_SYMBOLS.put("KES", "KSh");
        CURRENCY_SYMBOLS.put("KGS", "с");
        CURRENCY_SYMBOLS.put("KHR", "៛");
        CURRENCY_SYMBOLS.put("KID", "$");
        CURRENCY_SYMBOLS.put("KMF", "CF");
        CURRENCY_SYMBOLS.put("KRW", "₩");
        CURRENCY_SYMBOLS.put("KWD", "د.ك");
        CURRENCY_SYMBOLS.put("KYD", "CI$");
        CURRENCY_SYMBOLS.put("KZT", "₸");
        CURRENCY_SYMBOLS.put("LAK", "₭");
        CURRENCY_SYMBOLS.put("LBP", "ل.ل");
        CURRENCY_SYMBOLS.put("LKR", "Rs");
        CURRENCY_SYMBOLS.put("LRD", "L$");
        CURRENCY_SYMBOLS.put("LSL", "L");
        CURRENCY_SYMBOLS.put("LYD", "ل.د");
        CURRENCY_SYMBOLS.put("MAD", "د.م.");
        CURRENCY_SYMBOLS.put("MDL", "L");
        CURRENCY_SYMBOLS.put("MGA", "Ar");
        CURRENCY_SYMBOLS.put("MKD", "ден");
        CURRENCY_SYMBOLS.put("MMK", "K");
        CURRENCY_SYMBOLS.put("MNT", "₮");
        CURRENCY_SYMBOLS.put("MOP", "MOP$");
        CURRENCY_SYMBOLS.put("MRU", "UM");
        CURRENCY_SYMBOLS.put("MUR", "₨");
        CURRENCY_SYMBOLS.put("MVR", "ރ.");
        CURRENCY_SYMBOLS.put("MWK", "MK");
        CURRENCY_SYMBOLS.put("MXN", "$");
        CURRENCY_SYMBOLS.put("MYR", "RM");
        CURRENCY_SYMBOLS.put("MZN", "MT");
        CURRENCY_SYMBOLS.put("NAD", "N$");
        CURRENCY_SYMBOLS.put("NGN", "₦");
        CURRENCY_SYMBOLS.put("NIO", "C$");
        CURRENCY_SYMBOLS.put("NOK", "kr");
        CURRENCY_SYMBOLS.put("NPR", "₨");
        CURRENCY_SYMBOLS.put("NZD", "NZ$");
        CURRENCY_SYMBOLS.put("OMR", "ر.ع.");
        CURRENCY_SYMBOLS.put("PAB", "B/.");
        CURRENCY_SYMBOLS.put("PEN", "S/.");
        CURRENCY_SYMBOLS.put("PGK", "K");
        CURRENCY_SYMBOLS.put("PHP", "₱");
        CURRENCY_SYMBOLS.put("PKR", "₨");
        CURRENCY_SYMBOLS.put("PLN", "zł");
        CURRENCY_SYMBOLS.put("PYG", "₲");
        CURRENCY_SYMBOLS.put("QAR", "ر.ق");
        CURRENCY_SYMBOLS.put("RON", "lei");
        CURRENCY_SYMBOLS.put("RSD", "дин.");
        CURRENCY_SYMBOLS.put("RUB", "₽");
        CURRENCY_SYMBOLS.put("RWF", "FRw");
        CURRENCY_SYMBOLS.put("SAR", "ر.س");
        CURRENCY_SYMBOLS.put("SBD", "SI$");
        CURRENCY_SYMBOLS.put("SCR", "₨");
        CURRENCY_SYMBOLS.put("SDG", "ج.س.");
        CURRENCY_SYMBOLS.put("SEK", "kr");
        CURRENCY_SYMBOLS.put("SGD", "S$");
        CURRENCY_SYMBOLS.put("SHP", "£");
        CURRENCY_SYMBOLS.put("SLE", "Le");
        CURRENCY_SYMBOLS.put("SLL", "Le");
        CURRENCY_SYMBOLS.put("SOS", "Sh");
        CURRENCY_SYMBOLS.put("SRD", "SR$");
        CURRENCY_SYMBOLS.put("SSP", "£");
        CURRENCY_SYMBOLS.put("STN", "Db");
        CURRENCY_SYMBOLS.put("SYP", "ل.س");
        CURRENCY_SYMBOLS.put("SZL", "L");
        CURRENCY_SYMBOLS.put("THB", "฿");
        CURRENCY_SYMBOLS.put("TJS", "ЅМ");
        CURRENCY_SYMBOLS.put("TMT", "m");
        CURRENCY_SYMBOLS.put("TND", "د.ت");
        CURRENCY_SYMBOLS.put("TOP", "T$");
        CURRENCY_SYMBOLS.put("TRY", "₺");
        CURRENCY_SYMBOLS.put("TTD", "TT$");
        CURRENCY_SYMBOLS.put("TVD", "$");
        CURRENCY_SYMBOLS.put("TWD", "NT$");
        CURRENCY_SYMBOLS.put("TZS", "TSh");
        CURRENCY_SYMBOLS.put("UAH", "₴");
        CURRENCY_SYMBOLS.put("UGX", "USh");
        CURRENCY_SYMBOLS.put("UYU", "$U");
        CURRENCY_SYMBOLS.put("UZS", "so'm");
        CURRENCY_SYMBOLS.put("VES", "Bs.");
        CURRENCY_SYMBOLS.put("VND", "₫");
        CURRENCY_SYMBOLS.put("VUV", "VT");
        CURRENCY_SYMBOLS.put("WST", "WS$");
        CURRENCY_SYMBOLS.put("XAF", "FCFA");
        CURRENCY_SYMBOLS.put("XCD", "EC$");
        CURRENCY_SYMBOLS.put("XDR", "SDR");
        CURRENCY_SYMBOLS.put("XOF", "CFA");
        CURRENCY_SYMBOLS.put("XPF", "₣");
        CURRENCY_SYMBOLS.put("YER", "﷼");
        CURRENCY_SYMBOLS.put("ZAR", "R");
        CURRENCY_SYMBOLS.put("ZMW", "ZK");
        CURRENCY_SYMBOLS.put("ZWL", "Z$");
    }

    public static Currency getCurrency(String currencyCode) {
        Currency currency = new Currency();

        currency.setCurrencyCode(currencyCode);
        currency.setCurrencyName(CURRENCY_NAMES.getOrDefault(currencyCode, "Unknown CurrencyCode"));
        currency.setSymbol(CURRENCY_SYMBOLS.getOrDefault(currencyCode, ""));
        currency.setExchangeRate(EXCHANGE_RATES.getOrDefault(currencyCode, 0.0));

        return currency;
    }
}
